name: Daily Task

# Trigger the workflow every day at midnight UTC
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  run-daily-task:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify the Python version you need

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert

      # Convert Jupyter notebook to script and run it
      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to script CryptoKolScan/KolScanScanner.ipynb
